import { NextRequest, NextResponse } from 'next/server'
import { getSupabaseServerClient } from '@/lib/supabase/server'
import { withRateLimit } from '@/lib/rate-limit'
import { handleApiError } from '@/lib/server-error'

function money(cents: number) {
  const v = Math.round(cents || 0)
  return `$${(v / 100).toLocaleString(undefined, { maximumFractionDigits: 0 })}`
}

function severityRank(s: string) {
  return s === 'critical' ? 4 : s === 'high' ? 3 : s === 'medium' ? 2 : 1
}

/**
 * POST /api/leaks/email-report
 * Emails a leak report to the authenticated user's email.
 * Requires RESEND_API_KEY + RESEND_FROM_EMAIL.
 * Body: { stripe_connection_id?: string, limit?: number }
 */
export const POST = withRateLimit(async (req: NextRequest) => {
  try {
    const RESEND_API_KEY = process.env.RESEND_API_KEY
    const RESEND_FROM_EMAIL = process.env.RESEND_FROM_EMAIL
    if (!RESEND_API_KEY || !RESEND_FROM_EMAIL) {
      return NextResponse.json(
        { error: 'Email not configured. Set RESEND_API_KEY and RESEND_FROM_EMAIL.' },
        { status: 400 }
      )
    }

    const supabase = await getSupabaseServerClient()
    const { data: { user }, error: userError } = await supabase.auth.getUser()
    if (userError) throw userError
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const body = await req.json().catch(() => ({}))
    const stripe_connection_id: string | undefined = body?.stripe_connection_id
    const limit = Math.min(parseInt(body?.limit || '50', 10) || 50, 200)

    let q = supabase
      .from('revenue_leaks')
      .select('id,leak_type,lost_amount_cents,recoverable_amount_cents,severity,title,summary,recommended_action,created_at')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .limit(limit)

    if (stripe_connection_id) q = q.eq('stripe_connection_id', stripe_connection_id)
    const { data: leaks, error: leaksErr } = await q
    if (leaksErr) throw leaksErr

    const rows = (leaks || []).sort((a, b) => {
      const r = severityRank(b.severity) - severityRank(a.severity)
      if (r !== 0) return r
      return (b.recoverable_amount_cents || 0) - (a.recoverable_amount_cents || 0)
    })

    const lostTotal = rows.reduce((s, l) => s + (l.lost_amount_cents || 0), 0)
    const recTotal = rows.reduce((s, l) => s + (l.recoverable_amount_cents || 0), 0)

    const html = `
      <div style="font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto; line-height:1.5; color:#0f172a">
        <h2 style="margin:0 0 8px 0;">RevPilot — Revenue Leak Report</h2>
        <p style="margin:0 0 16px 0; color:#475569;">Summary of detected revenue leaks and highest-impact fixes.</p>
        <div style="display:flex; gap:12px; margin:0 0 16px 0;">
          <div style="padding:12px 14px; border:1px solid #e2e8f0; border-radius:12px;">
            <div style="font-size:12px; color:#64748b;">Estimated lost (monthly)</div>
            <div style="font-size:18px; font-weight:700;">${money(lostTotal)}</div>
          </div>
          <div style="padding:12px 14px; border:1px solid #e2e8f0; border-radius:12px;">
            <div style="font-size:12px; color:#64748b;">Estimated recoverable (monthly)</div>
            <div style="font-size:18px; font-weight:700;">${money(recTotal)}</div>
          </div>
        </div>
        <hr style="border:none; border-top:1px solid #e2e8f0; margin:16px 0;"/>
        ${rows.length ? rows.slice(0, 12).map((l) => `
          <div style="padding:12px 14px; border:1px solid #e2e8f0; border-radius:12px; margin:0 0 10px 0;">
            <div style="display:flex; justify-content:space-between; gap:10px;">
              <div style="font-weight:700;">${l.title}</div>
              <div style="font-size:12px; color:#475569;">${String(l.severity).toUpperCase()} · Recoverable ${money(l.recoverable_amount_cents || 0)}</div>
            </div>
            <div style="margin-top:6px; color:#334155;">${l.summary}</div>
            <div style="margin-top:8px; color:#0f172a;"><b>Fix:</b> ${l.recommended_action}</div>
          </div>
        `).join('') : `<p style="color:#475569;">No leaks detected yet. Run a scan from your dashboard.</p>`}
        <p style="margin:16px 0 0 0; font-size:12px; color:#64748b;">Generated by RevPilot Revenue Leak Detector.</p>
      </div>
    `

    const subject = `RevPilot Revenue Leak Report — Recoverable ${money(recTotal)}/mo`

    const resp = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: RESEND_FROM_EMAIL,
        to: user.email,
        subject,
        html,
      }),
    })

    let providerId: string | undefined
    if (!resp.ok) {
      const text = await resp.text().catch(() => '')
      return NextResponse.json({ error: `Failed to send email: ${resp.status} ${text}` }, { status: 500 })
    }

    try {
      const j = await resp.json().catch(() => null)
      providerId = j?.id
    } catch {
      // ignore
    }

    // best-effort log
    await supabase.from('leak_email_log').insert({
      user_id: user.id,
      stripe_connection_id: stripe_connection_id || null,
      sent_to: user.email,
      subject,
      provider_message_id: providerId || null,
    })

    return NextResponse.json({ ok: true })
  } catch (error) {
    return handleApiError(error)
  }
})
