-- Création de la table d'historique
CREATE TABLE IF NOT EXISTS metrics_history (
  id bigint generated by default as identity primary key,
  stripe_connection_id uuid references stripe_connections(id) not null,
  date date not null default current_date, -- La date de la "photo"
  mrr numeric not null default 0,
  active_subscriptions int not null default 0,
  
  -- Contrainte : Une seule photo par jour et par connexion
  UNIQUE(stripe_connection_id, date)
);

-- Activation de la sécurité (RLS)
ALTER TABLE metrics_history ENABLE ROW LEVEL SECURITY;

-- Politique : L'utilisateur ne peut voir que l'historique de ses propres connexions
-- (Note : Cela suppose une structure standard, adapte si nécessaire)
CREATE POLICY "Users can view own history" ON metrics_history
FOR SELECT USING (
  auth.uid() IN (
    SELECT user_id FROM stripe_connections 
    WHERE id = metrics_history.stripe_connection_id
  )
);